### ISSUE TITLE
config.php

### ISSUE THREAD

**Issue by dencho410** [cyberpaste/exchanger#1]
Что нужно сделать с config php,чтобы заработало?

**Comment by cyberpaste** [comment]
Нужно изменить доступы в бд
на свои
`    'database' => [
        'engine' => 'mysql',
        'databaseName' => 'exc',
        'databaseUser' => 'root',
        'databasePassword' => '',
    ],`
и импортировать базу из папки app/db.sql

**обращаю внимание, что весь функционал скрипта еще не доделан.** 
Инфу обновил https://github.com/cyberpaste/exchanger
